Repository code4romania/centrucivic, pull requests merged in 2022-12, with the labels that each got.

#18 fix: [C4R-1165] added max length to search field
  src/common/components/search-field/SearchField.tsx
Labels: bug :bug:, front-end

#17 fix: [C4R-1351] added connection with BE to send service feedback
  src/assets/locales/ro/translation.json
  src/common/components/feedback-form/FeedbackForm.tsx
  src/common/components/feedback-form/configs/FeedbackForm.config.ts
  src/common/interfaces/Feedback.interface.ts
  src/pages/contact/Contact.tsx
  src/pages/organizations/components/OrganizationItem.tsx
  src/services/public/PublicApi.queries.ts
  src/services/public/PublicApi.service.ts
Labels: bug :bug:, front-end

#14 fix: [C4R-1144] handle search on "Enter" key being pressed
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/search-field/SearchField.tsx
  src/common/components/service-search/ServiceSearch.tsx
  src/pages/services/components/ServiceList.tsx
Labels: bug :bug:, front-end

#15 fix: [C4R-1167] Blank spaces put in front of input are not ignored in search box
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/service-search/ServiceSearch.tsx
Labels: bug :bug:, front-end

#16 [C4R-1187] make direct call to cities query rather than through useCitiesQuery
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/service-filter-modal/ServiceFilterModal.tsx
  src/common/components/service-search/ServiceSearch.tsx
  src/services/nomenclature/Nomeclature.queries.ts
Labels: bug :bug:

#21 fix: [C4R-1401] fixed error message on failing to load service
  src/assets/locales/ro/translation.json
  src/common/components/shape-wrapper/ShapeWrapper.tsx
  src/pages/services/Service.tsx
Labels: bug :bug:, front-end

#19 fix: [C4R-1381, C4R-1396, C4R-1397] updated validations for contact and feedback forms
  src/assets/locales/ro/translation.json
  src/common/components/feedback-form/configs/FeedbackForm.config.ts
  src/common/helpers/CivicCenter.helper.ts
  src/common/helpers/Format.helper.ts
  src/pages/contact/configs/Contact.config.ts
  src/pages/services/components/ServiceItem.tsx
Labels: bug :bug:, front-end

#27 C4R-1061 - Fixed chip overflow
  src/common/components/chip-selection/ChipSelection.tsx
Labels: bug :bug:, front-end

#26 fix: [C4R-1396, C4R-1397] updated translations, changed feedback validation from onSubmit to onChange
  src/assets/locales/ro/translation.json
  src/common/components/feedback-form/FeedbackForm.tsx
  src/pages/contact/configs/Contact.config.ts
Labels: bug :bug:, front-end

#29 C4R-1161 - Partial fixed counter trigger on scroll and changed animat…
  src/pages/landing/components/counter/CounterItem.tsx
Labels: bug :bug:, front-end

#28 Bugfix/C4R-1367
  src/common/components/chip-selection/ChipSelection.tsx
  src/common/components/service-content/ServiceContent.tsx
  src/index.css
Labels: bug :bug:, front-end

#24 C4R-1260 - Removed exclamation mark from inputs
  src/common/components/textarea/Textarea.tsx
Labels: bug :bug:, front-end

#31 fix: [C4R-1209] changed contact data displayed when viewing one ong
  src/common/interfaces/Organization.interface.ts
  src/common/interfaces/Service.interface.ts
  src/pages/organizations/components/OrganizationDetails.tsx
Labels: bug :bug:, front-end

#32 refactor: [C4R-1513] cleaned up translation file
  src/assets/locales/ro/translation.json
  src/common/components/feedback-form/FeedbackForm.tsx
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/ngo-search/configs/NGOSearch.config.ts
  src/common/components/select/Select.tsx
  src/common/components/service-content/ServiceContent.tsx
  src/common/components/service-filter-modal/ServiceFilterModal.tsx
  src/common/components/service-search/ServiceSearch.tsx
  src/common/components/service-search/configs/ServiceSearch.config.ts
  src/common/helpers/CivicCenter.helper.ts
  src/pages/contact/Contact.tsx
  src/pages/landing/components/domains/Domains.tsx
  src/pages/organizations/Organization.tsx
  src/pages/organizations/components/OrganizationDetails.tsx
  src/pages/services/Service.tsx
  src/pages/services/components/ServiceItem.tsx
Labels: content, front-end
